export * from './admin.service';
import { AdminService } from './admin.service';
export * from './adminProductImage.service';
import { AdminProductImageService } from './adminProductImage.service';
export * from './order.service';
import { OrderService } from './order.service';
export * from './product.service';
import { ProductService } from './product.service';
export * from './productCategoru.service';
import { ProductCategoruService } from './productCategoru.service';
export * from './productImage.service';
import { ProductImageService } from './productImage.service';
export * from './productInCard.service';
import { ProductInCardService } from './productInCard.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AdminService, AdminProductImageService, OrderService, ProductService, ProductCategoruService, ProductImageService, ProductInCardService, UserService];
